export const LESSON_POINTS = 50;

export const LESSONS = [
  {
    id: "lesson-1",
    page: "lesson-1.html",
    title: "บทที่ 1",
    subtitle: "วิดีโอเริ่มต้น",
    status: "พร้อมเรียน",
    summary: "บทเริ่มต้นสำหรับเข้าใจภาพรวม AI และเริ่มใช้งานได้ง่ายขึ้น",
    description: "ดูวิดีโอแนะนำพื้นฐาน แล้วกดเรียนแล้วเพื่อรับ 50 คะแนนเข้าบัญชีของตัวเองได้ทันที",
    cover: "assets/courses/lesson-1-cover.png",
    videoId: "zwm5qU8XlmQ",
    available: true,
    progress: 5,
  },
  {
    id: "lesson-2",
    page: "lesson-2.html",
    title: "บทที่ 2",
    subtitle: "วิดีโอเรียนต่อ",
    status: "พร้อมเรียน",
    summary: "เรียนต่อจากบทนำด้วยวิดีโอที่เปิดได้ในหน้าเว็บ พร้อมรองรับการรับคะแนนเมื่อเรียนจบ",
    description: "ใช้วิดีโอนี้เป็นบทเรียนกลางของชุดเดียวกัน เหมาะกับการดูต่อเนื่องและใช้กดรับคะแนนสะสม 50 คะแนนหลังเรียนจบ",
    cover: "assets/banners/สร้างภาพโปรโมท.png",
    videoId: "AXYMdUUdn0Q",
    available: true,
    progress: 10,
  },
  {
    id: "lesson-3",
    page: "lesson-3.html",
    title: "บทที่ 3",
    subtitle: "วิดีโอเรียนต่อเนื่อง",
    status: "พร้อมเรียน",
    summary: "บทต่อเนื่องในชุดเดียวกัน รองรับการเรียนในหน้าเว็บและเก็บคะแนนแยกตามผู้ใช้",
    description: "วิดีโอบทนี้ทำงานต่อเนื่องกับบทที่ 2 เมื่อเรียนจบสามารถกดรับคะแนน 50 คะแนนได้อีก 1 ครั้งต่อผู้ใช้",
    cover: "assets/banners/สร้างวิดีโอ.png",
    videoId: "N-3oqzTD0sA",
    available: true,
    progress: 15,
  },
  {
    id: "lesson-4",
    page: "lesson.html?id=lesson-4",
    title: "บทที่ 4: Nano Banana เปลี่ยนชุดนายแบบและนางแบบ",
    subtitle: "เปลี่ยนลุคด้วย Nano Banana",
    status: "พร้อมเรียน",
    summary: "เรียนรู้วิธีเปลี่ยนชุดนายแบบและนางแบบให้เข้ากับสไตล์งานที่ต้องการ",
    description: "ฝึกใช้ Nano Banana เปลี่ยนเสื้อผ้าและลุคของนายแบบหรือนางแบบจากภาพต้นฉบับ พร้อมแนวทางเขียนคำสั่งให้ผลลัพธ์ดูสมจริง",
    cover: "assets/courses/lesson-4-cover.png",
    videoId: "3Mxapj8ogik",
    available: true,
    progress: 20,
  },
  {
    id: "lesson-5",
    page: "lesson.html?id=lesson-5",
    title: "บทที่ 5: Nano Banana ให้นายแบบถือสินค้า",
    subtitle: "นำสินค้าเข้าไปอยู่ในภาพบุคคล",
    status: "พร้อมเรียน",
    summary: "สร้างภาพนายแบบหรือนางแบบถือสินค้าได้อย่างเป็นธรรมชาติ",
    description: "เรียนรู้การนำภาพสินค้าไปวางร่วมกับนายแบบหรือนางแบบด้วย Nano Banana เพื่อทำภาพรีวิว ภาพโปรโมต และสื่อขายสินค้า",
    cover: "assets/courses/lesson-5-cover.png",
    videoId: "YN4JoXAKYCo",
    available: true,
    progress: 25,
  },
  {
    id: "lesson-6",
    page: "lesson.html?id=lesson-6",
    title: "บทที่ 6: Nano Banana สร้างภาพอาหาร",
    subtitle: "ทำภาพเมนูให้น่ากินและพร้อมขาย",
    status: "พร้อมเรียน",
    summary: "เริ่มสร้างภาพอาหารและเครื่องดื่มสำหรับร้านค้าด้วย Nano Banana",
    description: "ฝึกสร้างภาพอาหาร เครื่องดื่ม และสื่อโปรโมตร้านให้ดูน่ากิน พร้อมแนวทางสั่งงานเป็นภาษาไทยสำหรับนำไปใช้งานจริง",
    cover: "assets/courses/lesson-6-cover.png",
    videoId: "Jb24h6JffhQ",
    available: true,
    progress: 30,
  },
  {
    id: "lesson-7",
    page: "lesson.html?id=lesson-7",
    title: "บทที่ 7: Nano Banana สร้างรูปคู่",
    subtitle: "สร้างภาพคู่หลายสไตล์",
    status: "พร้อมเรียน",
    summary: "สร้างภาพคู่รัก ภาพแต่งงาน และภาพท่องเที่ยวจากภาพต้นฉบับ",
    description: "เรียนรู้การใช้ Nano Banana จัดองค์ประกอบบุคคลสองคนให้อยู่ในภาพเดียวกัน พร้อมปรับเสื้อผ้า ฉาก และบรรยากาศให้กลมกลืน",
    cover: "assets/courses/lesson-7-cover.png",
    videoId: "dWip_Dd_SBI",
    available: true,
    progress: 35,
  },
  {
    id: "lesson-8",
    page: "lesson.html?id=lesson-8",
    title: "บทที่ 8: Nano Banana สร้างรูปครอบครัว",
    subtitle: "รวมสมาชิกให้เป็นภาพครอบครัว",
    status: "พร้อมเรียน",
    summary: "สร้างภาพครอบครัวอบอุ่นได้หลายโอกาสและหลายสไตล์",
    description: "ฝึกใช้ Nano Banana รวมสมาชิกครอบครัว จัดท่าทาง เปลี่ยนฉาก และสร้างบรรยากาศให้เหมาะกับภาพครอบครัวแบบต่าง ๆ",
    cover: "assets/courses/lesson-8-cover.png",
    videoId: "_L8e-sm2Xqo",
    available: true,
    progress: 40,
  },
  {
    id: "lesson-9",
    page: "lesson.html?id=lesson-9",
    title: "บทที่ 9: 9 เทคนิคง่าย ๆ ในการใช้ Nano Banana",
    subtitle: "รวมเทคนิคที่มือใหม่ทำตามได้",
    status: "พร้อมเรียน",
    summary: "เรียน 9 เทคนิคพื้นฐานเพื่อใช้ Nano Banana ได้คล่องและเร็วขึ้น",
    description: "รวมเทคนิคการเขียนคำสั่งและปรับภาพที่ใช้ได้จริงกับงานบุคคล สินค้า อาหาร และคอนเทนต์ทั่วไป เหมาะสำหรับผู้เริ่มต้น",
    cover: "assets/courses/lesson-9-cover.png",
    videoId: "-0H34g2OhHA",
    available: true,
    progress: 45,
  },
  {
    id: "lesson-10",
    page: "lesson.html?id=lesson-10",
    title: "บทที่ 10: Nano Banana สร้างภาพสินค้ามืออาชีพ",
    subtitle: "ยกระดับภาพสินค้าให้พร้อมขาย",
    status: "พร้อมเรียน",
    summary: "สร้างภาพสินค้า แสง และฉากให้ดูเป็นงานโฆษณาระดับมืออาชีพ",
    description: "เรียนรู้การใช้ Nano Banana จัดแสง ฉาก และรายละเอียดสินค้าให้คมชัดสมจริง เหมาะกับภาพโปรดักต์และสื่อเชิงพาณิชย์",
    cover: "assets/courses/lesson-10-cover.png",
    videoId: "k9aNeF8odWM",
    available: true,
    progress: 50,
  },
  {
    id: "lesson-11",
    page: "lesson.html?id=lesson-11",
    title: "บทที่ 11: สร้างวิดีโอด้วย Kling AI",
    subtitle: "เริ่มต้นทำคลิป AI ด้วย Kling",
    status: "พร้อมเรียน",
    summary: "ทำความรู้จัก Kling AI และเริ่มสร้างวิดีโอจากข้อความหรือภาพ",
    description: "เรียนขั้นตอนพื้นฐานของ Kling AI ตั้งแต่เตรียมสื่อ เขียนคำสั่ง ไปจนถึงสร้างวิดีโอสำหรับคอนเทนต์และงานโฆษณา",
    cover: "assets/courses/lesson-11-cover.png",
    videoId: "yF4SxpxrhmA",
    available: true,
    progress: 55,
  },
  {
    id: "lesson-12",
    page: "lesson.html?id=lesson-12",
    title: "บทที่ 12: Kling AI Start Frame, End Frame และ Visual Hook",
    subtitle: "ควบคุมต้นคลิป ปลายคลิป และจุดดึงสายตา",
    status: "พร้อมเรียน",
    summary: "กำหนดภาพเริ่มต้นและภาพจบ พร้อมสร้าง Visual Hook ให้คลิปน่าสนใจ",
    description: "ฝึกใช้ Start Frame และ End Frame ใน Kling AI เพื่อควบคุมทิศทางวิดีโอ และออกแบบ Visual Hook ให้ดึงดูดตั้งแต่วินาทีแรก",
    cover: "assets/courses/lesson-12-cover.png",
    videoId: "Q6MSyUSkYXM",
    available: true,
    progress: 60,
  },
  {
    id: "lesson-13",
    page: "lesson.html?id=lesson-13",
    title: "บทที่ 13: ใช้ ChatGPT ช่วยเขียน Prompt",
    subtitle: "ให้ AI ช่วยวางคำสั่งอย่างเป็นระบบ",
    status: "พร้อมเรียน",
    summary: "ใช้ ChatGPT ช่วยคิดและปรับ Prompt สำหรับงาน AI ประเภทต่าง ๆ",
    description: "เรียนวิธีบอกเป้าหมาย บริบท และรูปแบบผลลัพธ์ให้ ChatGPT ช่วยร่าง Prompt ที่ชัดเจน ก่อนนำไปใช้สร้างภาพ วิดีโอ หรือคอนเทนต์",
    cover: "assets/banners/เริ่มต้นใช้งาน.png",
    videoId: "rJOY6vsoHoQ",
    available: true,
    progress: 65,
  },
  {
    id: "lesson-14",
    page: "lesson.html?id=lesson-14",
    title: "บทที่ 14: Veo + JSON Prompt เบื้องต้น",
    subtitle: "เขียนคำสั่งวิดีโอแบบมีโครงสร้าง",
    status: "พร้อมเรียน",
    summary: "เริ่มใช้ JSON Prompt เพื่อควบคุมฉาก กล้อง การเคลื่อนไหว และสไตล์",
    description: "ทำความเข้าใจส่วนประกอบพื้นฐานของ JSON Prompt และนำไปใช้กับ Veo เพื่อสร้างวิดีโอที่กำหนดรายละเอียดได้เป็นระบบมากขึ้น",
    cover: "assets/courses/lesson-14-cover.png",
    videoId: "9s1ZKcmrURk",
    available: true,
    progress: 70,
  },
  {
    id: "lesson-15",
    page: "lesson.html?id=lesson-15",
    title: "บทที่ 15: Upscale Image ขยายภาพให้คมชัด",
    subtitle: "เพิ่มความละเอียดให้ภาพพร้อมใช้งาน",
    status: "พร้อมเรียน",
    summary: "ขยายและเพิ่มความคมชัดให้ภาพบุคคล สินค้า และภาพท่องเที่ยว",
    description: "เรียนรู้วิธี Upscale ภาพที่มีความละเอียดต่ำให้ดูคมชัดขึ้น พร้อมแนวทางเลือกใช้กับงานส่วนตัวและงานเชิงพาณิชย์",
    cover: "assets/courses/lesson-15-cover.png",
    videoId: "giimIh-nIdY",
    available: true,
    progress: 75,
  },
  {
    id: "lesson-16",
    page: "lesson.html?id=lesson-16",
    title: "บทที่ 16: Nano Banana โปรโมตสินค้าด้วยข้อความภาษาไทย",
    subtitle: "สร้างภาพขายของที่อ่านภาษาไทยได้",
    status: "พร้อมเรียน",
    summary: "ออกแบบภาพโปรโมตสินค้า พร้อมหัวข้อ รายละเอียด และราคาเป็นภาษาไทย",
    description: "ฝึกใช้ Nano Banana สร้างภาพขายสินค้าที่มีข้อความภาษาไทย จัดวางข้อมูลสำคัญ และทำให้งานพร้อมนำไปใช้โปรโมตได้รวดเร็ว",
    cover: "assets/courses/lesson-16-cover.png",
    videoId: "uP4XV6vBlTE",
    available: true,
    progress: 80,
  },
  {
    id: "lesson-17",
    page: "lesson.html?id=lesson-17",
    title: "บทที่ 17: Nano Banana ทำป้าย Info ต่าง ๆ",
    subtitle: "สร้างป้ายข้อมูลสำหรับออนไลน์และออฟไลน์",
    status: "พร้อมเรียน",
    summary: "ทำป้าย Wi-Fi ป้ายแจ้งเตือน เมนู และป้ายข้อมูลธุรกิจด้วย AI",
    description: "เรียนรู้การออกแบบป้าย Info หลายรูปแบบด้วย Nano Banana ตั้งแต่ระบุข้อความ วัสดุ และสไตล์ ไปจนถึงเตรียมภาพสำหรับใช้งานจริง",
    cover: "assets/courses/lesson-17-cover.png",
    videoId: "qurUCwxdtZk",
    available: true,
    progress: 85,
  },
  {
    id: "lesson-18",
    page: "lesson.html?id=lesson-18",
    title: "บทที่ 18: Suno AI เบื้องต้น",
    subtitle: "เริ่มสร้างเพลงด้วย AI",
    status: "พร้อมเรียน",
    summary: "ทำความรู้จัก Suno AI และเริ่มสร้างเพลงได้แม้ไม่มีพื้นฐานดนตรี",
    description: "เรียนขั้นตอนพื้นฐานของ Suno AI ตั้งแต่กำหนดเนื้อหา เลือกสไตล์เพลง ไปจนถึงสร้างเพลงสำหรับคอนเทนต์และงานทดลอง",
    cover: "assets/courses/lesson-18-cover.png",
    videoId: "Y-jezHDazJ4",
    available: true,
    progress: 90,
  },
  {
    id: "lesson-19",
    page: "lesson.html?id=lesson-19",
    title: "บทที่ 19: NotebookLM",
    subtitle: "สรุปและค้นข้อมูลจากเอกสารด้วย AI",
    status: "พร้อมเรียน",
    summary: "ใช้ NotebookLM ช่วยสรุป ถามตอบ และสร้างเสียงสรุปจากแหล่งข้อมูล",
    description: "เรียนรู้การเพิ่มเอกสารเข้า NotebookLM แล้วใช้ AI ช่วยจับประเด็น สร้างคำถาม และสรุปข้อมูลสำหรับงานเรียน งานสอน และงานวิจัย",
    cover: "assets/courses/lesson-19-cover.png",
    videoId: "cLNhIWBADBs",
    available: true,
    progress: 95,
  },
  {
    id: "lesson-20",
    page: "lesson.html?id=lesson-20",
    title: "บทที่ 20: Google Storybook",
    subtitle: "สร้างนิทานพร้อมภาพและเสียงด้วย AI",
    status: "พร้อมเรียน",
    summary: "เริ่มสร้างนิทานพร้อมภาพประกอบและเสียงเล่าด้วย Google Storybook",
    description: "เรียนรู้การกำหนดเรื่อง ตัวละคร และสไตล์ภาพ เพื่อให้ Google Storybook ช่วยสร้างนิทานที่เหมาะกับเด็ก การเรียนรู้ และงานคอนเทนต์",
    cover: "assets/courses/lesson-20-cover.png",
    videoId: "QkLsITaIWiU",
    available: true,
    progress: 100,
  },
];

export function getLessonById(lessonId) {
  return LESSONS.find((lesson) => lesson.id === lessonId) || null;
}

export function getLessonIndex(lessonId) {
  return LESSONS.findIndex((lesson) => lesson.id === lessonId);
}
