(() => {
  const covers = {
    restaurant: "assets/banners/โปรโมทร้านอาหาร.png",
    fashion: "assets/banners/ภาพสินค้า.png",
    "real-estate": "assets/banners/ทำการตลาดด้วย.png",
    automotive: "assets/banners/โฆษณา.png",
    beauty: "assets/banners/ภาพสินค้า.png",
    ecommerce: "assets/banners/สร้างภาพโปรโมท.png",
    "local-service": "assets/banners/เริ่มต้นใช้งาน.png",
    education: "assets/banners/สร้างวิดีโอ.png",
    ads: "assets/banners/โฆษณา.png",
    video: "assets/banners/สร้างวิดีโอ.png",
  };

  window.GIVEME_PROMPT_CATEGORIES = [
    { id: "restaurant", name: "ร้านอาหาร / คาเฟ่", icon: "🍜", count: 6, useCase: "โปรโมทเมนู ดึงลูกค้าใหม่ ทำคอนเทนต์หน้าร้าน และเพิ่มยอดสั่งเดลิเวอรี่" },
    { id: "fashion", name: "เสื้อผ้า / แฟชั่น", icon: "👗", count: 5, useCase: "ทำแคปชันไลฟ์ขายของ เปิดตัวคอลเลกชัน และเขียนโพสต์ปิดการขาย" },
    { id: "real-estate", name: "บ้าน / คอนโด / อสังหา", icon: "🏠", count: 5, useCase: "เขียนโพสต์ขายบ้าน ทำสคริปต์พาชม และสรุปจุดเด่นโครงการให้เข้าใจง่าย" },
    { id: "automotive", name: "รถยนต์ / ไฟแนนซ์", icon: "🚗", count: 4, useCase: "ทำคอนเทนต์รถมือสอง โปรไฟแนนซ์ เปรียบเทียบรุ่น และปิดข้อกังวลลูกค้า" },
    { id: "beauty", name: "ความงาม / คลินิก", icon: "✨", count: 5, useCase: "สร้างโพสต์ก่อน-หลัง สกินแคร์ คลินิกความงาม และแคมเปญความน่าเชื่อถือ" },
    { id: "ecommerce", name: "สินค้าออนไลน์", icon: "🛒", count: 4, useCase: "เขียนหน้าสินค้า โปรโมชั่น Marketplace รีวิว และคำตอบแชตลูกค้า" },
    { id: "local-service", name: "บริการท้องถิ่น", icon: "🧰", count: 4, useCase: "ทำโพสต์บริการรายพื้นที่ เช่น แอร์ ซ่อมบ้าน ร้านซักรีด ขนส่ง และงานช่าง" },
    { id: "education", name: "คอร์สเรียน / โค้ช", icon: "🎓", count: 3, useCase: "ออกแบบข้อเสนอคอร์ส เขียนหน้าเซลส์เพจ และทำคอนเทนต์ให้คนสมัครเรียน" },
    { id: "ads", name: "วิเคราะห์ Ads / Hook", icon: "📣", count: 3, useCase: "หา Hook ใหม่ วิเคราะห์โฆษณา และปรับข้อความให้เหมาะกับ Facebook/TikTok" },
    { id: "video", name: "สคริปต์วิดีโอสั้น", icon: "🎬", count: 1, useCase: "ทำสคริปต์ Reels/TikTok พร้อม shot list และ CTA สำหรับธุรกิจ" },
  ];

  window.GIVEME_PROMPTS = [
    {
      id: "restaurant-new-menu",
      title: "โปรโมทเมนูใหม่ให้คนอยากลอง",
      category: "restaurant",
      businessType: "ร้านอาหาร",
      summary: "เปลี่ยนเมนูธรรมดาให้เป็นโพสต์ขายที่เห็นภาพ รู้สึกหิว และอยากสั่งทันที",
      prompt: "ช่วยเขียนโพสต์โปรโมทเมนูใหม่ของร้านอาหารชื่อ [ชื่อร้าน] เมนูคือ [ชื่อเมนู] จุดเด่นคือ [วัตถุดิบ/รสชาติ/ราคา] กลุ่มลูกค้าคือ [กลุ่มเป้าหมาย] ต้องการโทน [อบอุ่น/สนุก/พรีเมียม] ขอ 3 เวอร์ชัน: สั้นสำหรับ Facebook, caption สำหรับ Instagram และข้อความยิงแอด พร้อม CTA ให้สั่งซื้อหรือจองโต๊ะ",
      tags: ["เมนูใหม่", "ร้านอาหาร", "Facebook"],
      rating: 4.9,
      uses: 1240,
      cover: covers.restaurant,
      featured: true,
    },
    {
      id: "restaurant-delivery-promo",
      title: "เพิ่มยอดเดลิเวอรี่ช่วงเย็น",
      category: "restaurant",
      businessType: "ร้านอาหาร / เดลิเวอรี่",
      summary: "ทำโปรโมชันอาหารเย็นให้ลูกค้าตัดสินใจสั่งง่ายขึ้น",
      prompt: "เขียนแคมเปญเดลิเวอรี่สำหรับร้าน [ชื่อร้าน] ช่วงเวลา [ช่วงเวลา] เมนูแนะนำ [เมนู] โปรโมชัน [โปร] จุดเด่น [อร่อย/เร็ว/คุ้ม/สะอาด] ขอ headline 5 แบบ, caption 3 แบบ, ข้อความบนภาพ 5 แบบ และ CTA สำหรับ LINE MAN/Grab/Foodpanda",
      tags: ["เดลิเวอรี่", "โปรโมชัน", "อาหารเย็น"],
      rating: 4.8,
      uses: 980,
      cover: covers.restaurant,
      featured: false,
    },
    {
      id: "cafe-checkin",
      title: "ชวนลูกค้าเช็กอินคาเฟ่",
      category: "restaurant",
      businessType: "คาเฟ่",
      summary: "สร้างโพสต์ให้ร้านดูน่าแวะ ถ่ายรูปสวย และเหมาะกับการแชร์",
      prompt: "ช่วยคิดโพสต์ชวนลูกค้ามาเช็กอินคาเฟ่ [ชื่อร้าน] จุดเด่นคือ [มุมถ่ายรูป/เครื่องดื่ม/บรรยากาศ] อยู่ย่าน [พื้นที่] กลุ่มลูกค้า [วัยรุ่น/คนทำงาน/ครอบครัว] ขอ caption 5 แบบ, hashtag 20 คำ, และไอเดียรูปประกอบ 5 รูป",
      tags: ["คาเฟ่", "เช็กอิน", "คอนเทนต์"],
      rating: 4.8,
      uses: 870,
      cover: covers.restaurant,
      featured: true,
    },
    {
      id: "restaurant-review-reply",
      title: "ตอบรีวิวลูกค้าแบบมืออาชีพ",
      category: "restaurant",
      businessType: "ร้านอาหาร",
      summary: "ตอบทั้งรีวิวดีและรีวิวลบให้ดูใส่ใจและรักษาภาพลักษณ์ร้าน",
      prompt: "ช่วยเขียนคำตอบรีวิวลูกค้าร้านอาหาร [ชื่อร้าน] โดยมีรีวิวว่า: [ใส่ข้อความรีวิว] ขอคำตอบ 3 โทน: สุภาพสั้น, อบอุ่นจริงใจ, และมืออาชีพสำหรับเคสรีวิวลบ โดยไม่โต้เถียงลูกค้าและมีประโยคชวนกลับมาใช้บริการอีกครั้ง",
      tags: ["รีวิว", "บริการลูกค้า", "ภาพลักษณ์"],
      rating: 4.7,
      uses: 640,
      cover: covers.restaurant,
      featured: false,
    },
    {
      id: "restaurant-set-menu",
      title: "ขายเซ็ตเมนูให้ดูคุ้ม",
      category: "restaurant",
      businessType: "ร้านอาหาร",
      summary: "ช่วยจัดคำพูดให้เซ็ตอาหารดูคุ้ม เหมาะกับครอบครัวหรือออฟฟิศ",
      prompt: "ช่วยเขียนข้อความขายเซ็ตเมนู [ชื่อเซ็ต] ราคา [ราคา] เหมาะสำหรับ [จำนวนคน/โอกาส] เมนูในเซ็ตมี [รายการอาหาร] จุดเด่นคือ [คุ้ม/อิ่ม/ทำสด] ขอข้อความบนภาพ, caption, และประโยคปิดการขายสำหรับแชตลูกค้า",
      tags: ["เซ็ตเมนู", "คุ้มค่า", "ปิดการขาย"],
      rating: 4.8,
      uses: 720,
      cover: covers.restaurant,
      featured: false,
    },
    {
      id: "restaurant-grand-opening",
      title: "ประกาศเปิดร้านใหม่",
      category: "restaurant",
      businessType: "ร้านอาหาร / คาเฟ่",
      summary: "ทำโพสต์เปิดร้านให้คนในพื้นที่รู้จักและอยากมาลอง",
      prompt: "ช่วยเขียนโพสต์เปิดร้านใหม่ชื่อ [ชื่อร้าน] ประเภทร้าน [ประเภท] อยู่ที่ [ทำเล] จุดเด่น [เมนู/บรรยากาศ/ราคา] โปรเปิดร้าน [โปร] ขอ headline, caption ยาว, caption สั้น, ข้อความบนภาพ และ CTA ให้ลูกค้าปักหมุดมา",
      tags: ["เปิดร้าน", "ร้านใหม่", "พื้นที่"],
      rating: 4.9,
      uses: 1090,
      cover: covers.restaurant,
      featured: true,
    },
    {
      id: "fashion-live-script",
      title: "สคริปต์ไลฟ์ขายเสื้อผ้า",
      category: "fashion",
      businessType: "เสื้อผ้า / ไลฟ์ขายของ",
      summary: "วางลำดับพูดให้ไลฟ์ไม่น่าเบื่อและปิดออเดอร์ได้ชัดเจน",
      prompt: "ช่วยเขียนสคริปต์ไลฟ์ขายเสื้อผ้า [ประเภทสินค้า] ของร้าน [ชื่อร้าน] จุดเด่น [ผ้า/ทรง/ไซซ์/ราคา] โปร [โปร] ขอ flow 30 นาที ตั้งแต่เปิดไลฟ์ แนะนำสินค้า กระตุ้นคอมเมนต์ ปิดการขาย และตอบคำถามเรื่องไซซ์/ค่าส่ง",
      tags: ["ไลฟ์ขายของ", "แฟชั่น", "สคริปต์"],
      rating: 4.9,
      uses: 1320,
      cover: covers.fashion,
      featured: true,
    },
    {
      id: "fashion-new-collection",
      title: "เปิดตัวคอลเลกชันใหม่",
      category: "fashion",
      businessType: "แบรนด์เสื้อผ้า",
      summary: "ทำให้สินค้าดูมีสไตล์และมีเหตุผลให้ซื้อทันที",
      prompt: "เขียนโพสต์เปิดตัวคอลเลกชัน [ชื่อคอลเลกชัน] สำหรับแบรนด์ [ชื่อแบรนด์] สไตล์ [มินิมอล/เกาหลี/ลักชัวรี่/สตรีท] จุดเด่น [วัสดุ/ดีไซน์/ใส่ได้หลายโอกาส] ขอ caption 5 แบบ, headline บนภาพ 5 แบบ และ tagline สั้น",
      tags: ["คอลเลกชัน", "แบรนด์", "แฟชั่น"],
      rating: 4.8,
      uses: 760,
      cover: covers.fashion,
      featured: false,
    },
    {
      id: "fashion-size-objection",
      title: "ตอบข้อกังวลเรื่องไซซ์",
      category: "fashion",
      businessType: "เสื้อผ้าออนไลน์",
      summary: "ช่วยตอบแชตลูกค้าที่ลังเลเรื่องไซซ์ ทรง และการเปลี่ยนสินค้า",
      prompt: "ช่วยเขียนคำตอบแชตลูกค้าที่ถามเรื่องไซซ์สินค้า [ชื่อสินค้า] ขนาด [ไซซ์] รายละเอียดทรง [ทรง] นโยบายเปลี่ยนสินค้า [เงื่อนไข] ขอคำตอบแบบสุภาพ น่าเชื่อถือ และช่วยให้ลูกค้าตัดสินใจง่ายขึ้น 5 เวอร์ชัน",
      tags: ["แชตลูกค้า", "ไซซ์", "ปิดการขาย"],
      rating: 4.7,
      uses: 610,
      cover: covers.fashion,
      featured: false,
    },
    {
      id: "fashion-product-photo",
      title: "ไอเดียภาพสินค้าเสื้อผ้า",
      category: "fashion",
      businessType: "แฟชั่น",
      summary: "ออกแบบมุมถ่ายภาพสินค้าให้ดูแพงขึ้นและขายง่ายขึ้น",
      prompt: "ช่วยคิดไอเดียถ่ายภาพสินค้าเสื้อผ้า [ประเภท] สไตล์แบรนด์ [สไตล์] กลุ่มลูกค้า [กลุ่ม] ขอ 8 ไอเดียภาพ พร้อมฉาก แสง ท่าโพส พร็อพ และข้อความบนภาพที่ควรใส่",
      tags: ["ภาพสินค้า", "ไอเดียถ่ายรูป", "แบรนด์"],
      rating: 4.8,
      uses: 840,
      cover: covers.fashion,
      featured: true,
    },
    {
      id: "fashion-clearance-sale",
      title: "โปรเคลียร์สต๊อกให้ไม่ดูถูก",
      category: "fashion",
      businessType: "เสื้อผ้า",
      summary: "ทำโปรลดราคาให้ยังดูดี ไม่ทำให้แบรนด์เสียภาพลักษณ์",
      prompt: "เขียนแคมเปญเคลียร์สต๊อกสินค้าแฟชั่น [ประเภทสินค้า] ส่วนลด [ส่วนลด] จำนวนจำกัด [จำนวน] ขอข้อความที่ทำให้ดูเป็นโอกาสพิเศษ ไม่ใช่ของค้าง พร้อม headline 5 แบบ และ caption 3 แบบ",
      tags: ["ลดราคา", "เคลียร์สต๊อก", "โปรโมชัน"],
      rating: 4.7,
      uses: 690,
      cover: covers.fashion,
      featured: false,
    },
    {
      id: "real-estate-house-sale",
      title: "โพสต์ขายบ้านให้น่าสนใจ",
      category: "real-estate",
      businessType: "อสังหา",
      summary: "สรุปจุดเด่นบ้านให้ลูกค้าเห็นประโยชน์ ไม่ใช่แค่รายละเอียดทรัพย์",
      prompt: "ช่วยเขียนโพสต์ขายบ้าน [ประเภทบ้าน] ทำเล [ทำเล] ราคา [ราคา] จุดเด่น [พื้นที่/ห้อง/ใกล้สถานที่/รีโนเวท] กลุ่มเป้าหมาย [ครอบครัว/นักลงทุน/คนทำงาน] ขอ caption, headline, bullet จุดเด่น และ CTA นัดชมบ้าน",
      tags: ["ขายบ้าน", "อสังหา", "นัดชม"],
      rating: 4.9,
      uses: 1180,
      cover: covers["real-estate"],
      featured: true,
    },
    {
      id: "real-estate-condo-rent",
      title: "ปล่อยเช่าคอนโดให้ปิดไว",
      category: "real-estate",
      businessType: "คอนโด",
      summary: "ทำประกาศเช่าคอนโดให้ครบและตอบโจทย์คนหาห้อง",
      prompt: "เขียนประกาศปล่อยเช่าคอนโด [ชื่อโครงการ] ทำเล [ทำเล] ราคาเช่า [ราคา] ขนาด [ขนาด] เฟอร์นิเจอร์ [รายละเอียด] จุดเด่น [ใกล้ BTS/วิว/เครื่องใช้ไฟฟ้า] ขอข้อความสั้นสำหรับ Facebook Marketplace และข้อความยาวสำหรับเพจ",
      tags: ["คอนโด", "เช่า", "Marketplace"],
      rating: 4.8,
      uses: 920,
      cover: covers["real-estate"],
      featured: false,
    },
    {
      id: "real-estate-tour-script",
      title: "สคริปต์พาชมบ้าน",
      category: "real-estate",
      businessType: "นายหน้า / โครงการ",
      summary: "ทำสคริปต์วิดีโอพาชมให้เป็นลำดับและปิดท้ายชวนติดต่อ",
      prompt: "เขียนสคริปต์วิดีโอพาชม [บ้าน/คอนโด] ความยาว 60 วินาที สำหรับทรัพย์ [รายละเอียด] จุดเด่น [จุดเด่น] ราคา [ราคา] ขอ hook 3 วินาทีแรก, shot list, voice over, ข้อความบนจอ และ CTA นัดชม",
      tags: ["วิดีโอ", "พาชมบ้าน", "นายหน้า"],
      rating: 4.8,
      uses: 740,
      cover: covers["real-estate"],
      featured: false,
    },
    {
      id: "real-estate-investor",
      title: "ขายทรัพย์ให้นักลงทุน",
      category: "real-estate",
      businessType: "อสังหาเพื่อการลงทุน",
      summary: "เน้นตัวเลข ผลตอบแทน และเหตุผลเชิงลงทุนให้ชัด",
      prompt: "ช่วยเขียนโพสต์ขายทรัพย์สำหรับนักลงทุน รายละเอียดทรัพย์ [รายละเอียด] ราคา [ราคา] ค่าเช่าประมาณ [ค่าเช่า] จุดแข็งทำเล [จุดแข็ง] ขอวิเคราะห์ผลตอบแทนคร่าว ๆ, bullet ข้อดี, ความเสี่ยงที่ควรรู้ และ CTA ให้ทักเพื่อขอข้อมูลเพิ่ม",
      tags: ["นักลงทุน", "ROI", "ทรัพย์ลงทุน"],
      rating: 4.7,
      uses: 520,
      cover: covers["real-estate"],
      featured: false,
    },
    {
      id: "real-estate-objection",
      title: "ตอบข้อกังวลลูกค้าอสังหา",
      category: "real-estate",
      businessType: "นายหน้า",
      summary: "เตรียมคำตอบเรื่องราคา ทำเล ค่าส่วนกลาง และการกู้",
      prompt: "ช่วยเขียนชุดคำตอบข้อกังวลลูกค้าอสังหา 10 ข้อ สำหรับทรัพย์ [รายละเอียด] เช่น ราคาแพงไป ทำเลไกล กู้ผ่านไหม ค่าส่วนกลางเท่าไร ขอคำตอบแบบมืออาชีพ ไม่กดดัน และชวนลูกค้านัดดูทรัพย์",
      tags: ["Objection", "นายหน้า", "ปิดการขาย"],
      rating: 4.8,
      uses: 660,
      cover: covers["real-estate"],
      featured: false,
    },
    {
      id: "car-used-sale",
      title: "โพสต์ขายรถมือสอง",
      category: "automotive",
      businessType: "รถมือสอง",
      summary: "ทำให้รถดูน่าเชื่อถือและตอบคำถามสำคัญครบ",
      prompt: "เขียนโพสต์ขายรถมือสอง รุ่น [รุ่นรถ] ปี [ปี] ราคา [ราคา] เลขไมล์ [เลขไมล์] จุดเด่น [สภาพ/ประวัติ/แต่งเพิ่ม] เงื่อนไขไฟแนนซ์ [เงื่อนไข] ขอ caption, bullet จุดเด่น, ข้อความบนภาพ และ CTA นัดดูรถ",
      tags: ["รถมือสอง", "ไฟแนนซ์", "นัดดูรถ"],
      rating: 4.9,
      uses: 1060,
      cover: covers.automotive,
      featured: true,
    },
    {
      id: "car-finance",
      title: "อธิบายไฟแนนซ์ให้เข้าใจง่าย",
      category: "automotive",
      businessType: "เต็นท์รถ",
      summary: "แปลงเงื่อนไขไฟแนนซ์ให้ลูกค้าอ่านแล้วไม่สับสน",
      prompt: "ช่วยเขียนโพสต์อธิบายโปรไฟแนนซ์สำหรับรถ [รุ่น] ราคา [ราคา] ดาวน์ [ดาวน์] ผ่อน [ผ่อน] ระยะเวลา [งวด] ขอข้อความที่เข้าใจง่าย ไม่ชวนเข้าใจผิด พร้อม FAQ 8 ข้อ และ CTA ให้ส่งเอกสารประเมิน",
      tags: ["ไฟแนนซ์", "ผ่อนรถ", "FAQ"],
      rating: 4.8,
      uses: 720,
      cover: covers.automotive,
      featured: false,
    },
    {
      id: "car-comparison",
      title: "เปรียบเทียบรถ 2 รุ่น",
      category: "automotive",
      businessType: "คอนเทนต์รถ",
      summary: "ช่วยลูกค้าเลือกจากการใช้งานจริง ไม่ใช่แค่สเปก",
      prompt: "ช่วยเปรียบเทียบรถ [รุ่น A] กับ [รุ่น B] สำหรับลูกค้า [กลุ่มเป้าหมาย] โดยเทียบด้านราคา ค่าใช้จ่าย การใช้งานในเมือง เดินทางไกล ความคุ้มค่า และเหมาะกับใคร ขอเป็นตารางและสรุปคำแนะนำท้ายโพสต์",
      tags: ["เปรียบเทียบ", "รถยนต์", "คอนเทนต์"],
      rating: 4.7,
      uses: 540,
      cover: covers.automotive,
      featured: false,
    },
    {
      id: "car-after-sales",
      title: "สร้างความมั่นใจหลังการขาย",
      category: "automotive",
      businessType: "เต็นท์รถ / ศูนย์บริการ",
      summary: "เน้นประกัน บริการหลังขาย และความน่าเชื่อถือ",
      prompt: "เขียนโพสต์สร้างความมั่นใจให้ลูกค้าที่กำลังซื้อรถจาก [ชื่อร้าน] จุดแข็งคือ [รับประกัน/ตรวจสภาพ/บริการหลังขาย] ขอ headline, caption และรายการคำมั่นสัญญาที่ทำให้ลูกค้ากล้าทักสอบถาม",
      tags: ["บริการหลังขาย", "ความน่าเชื่อถือ", "รถยนต์"],
      rating: 4.7,
      uses: 490,
      cover: covers.automotive,
      featured: false,
    },
    {
      id: "beauty-before-after",
      title: "โพสต์ Before/After คลินิก",
      category: "beauty",
      businessType: "คลินิกความงาม",
      summary: "สื่อสารผลลัพธ์แบบน่าเชื่อถือ ไม่โอเวอร์เคลม",
      prompt: "ช่วยเขียนโพสต์ Before/After สำหรับบริการ [ชื่อบริการ] ของคลินิก [ชื่อคลินิก] ผลลัพธ์ที่ต้องการสื่อคือ [ผลลัพธ์] เงื่อนไข [จำนวนครั้ง/ระยะเวลา] ขอข้อความแบบน่าเชื่อถือ มี disclaimer ว่าผลลัพธ์ขึ้นกับแต่ละบุคคล และ CTA นัดปรึกษา",
      tags: ["คลินิก", "Before After", "ความงาม"],
      rating: 4.9,
      uses: 1280,
      cover: covers.beauty,
      featured: true,
    },
    {
      id: "beauty-skincare-launch",
      title: "เปิดตัวสกินแคร์ใหม่",
      category: "beauty",
      businessType: "สกินแคร์",
      summary: "ทำให้สินค้าเห็นปัญหา เห็นประโยชน์ และอยากทดลอง",
      prompt: "เขียนโพสต์เปิดตัวสกินแคร์ [ชื่อสินค้า] สำหรับปัญหา [ปัญหาผิว] ส่วนผสมเด่น [ส่วนผสม] เหมาะกับ [กลุ่มผิว] ขอ hook 5 แบบ, caption, bullet benefit, ข้อความบนภาพ และ CTA ซื้อหรือทักแชต",
      tags: ["สกินแคร์", "สินค้าใหม่", "Benefit"],
      rating: 4.8,
      uses: 990,
      cover: covers.beauty,
      featured: true,
    },
    {
      id: "beauty-salon-package",
      title: "แพ็กเกจร้านเสริมสวย",
      category: "beauty",
      businessType: "ร้านเสริมสวย",
      summary: "ขายแพ็กเกจทำผม ทำเล็บ หรือสปาให้ดูคุ้มและจองง่าย",
      prompt: "ช่วยเขียนโปรโมชันแพ็กเกจร้าน [ชื่อร้าน] บริการ [บริการ] ราคา [ราคา] ระยะเวลาโปร [ช่วงเวลา] จุดเด่น [ช่าง/ผลิตภัณฑ์/บรรยากาศ] ขอ caption 3 แบบ, headline 5 แบบ และข้อความตอบลูกค้าที่ถามรายละเอียด",
      tags: ["ร้านเสริมสวย", "แพ็กเกจ", "จองคิว"],
      rating: 4.8,
      uses: 760,
      cover: covers.beauty,
      featured: false,
    },
    {
      id: "beauty-trust-faq",
      title: "FAQ สร้างความเชื่อมั่น",
      category: "beauty",
      businessType: "คลินิก / สกินแคร์",
      summary: "เตรียมคำตอบคำถามเรื่องความปลอดภัย ราคา และผลลัพธ์",
      prompt: "ช่วยเขียน FAQ 12 ข้อสำหรับบริการ/สินค้า [ชื่อ] ครอบคลุมเรื่องราคา ความปลอดภัย เหมาะกับใคร ระยะเห็นผล ข้อควรระวัง และการดูแลหลังใช้บริการ ขอคำตอบแบบสุภาพและน่าเชื่อถือ",
      tags: ["FAQ", "Trust", "ความงาม"],
      rating: 4.7,
      uses: 620,
      cover: covers.beauty,
      featured: false,
    },
    {
      id: "beauty-influencer-brief",
      title: "บรีฟอินฟลูเอนเซอร์สายบิวตี้",
      category: "beauty",
      businessType: "แบรนด์ความงาม",
      summary: "ทำบรีฟให้รีวิวดูธรรมชาติและสื่อสารจุดขายครบ",
      prompt: "ช่วยเขียนบรีฟงานรีวิวสำหรับอินฟลูเอนเซอร์สินค้า [ชื่อสินค้า] จุดขาย [จุดขาย] กลุ่มเป้าหมาย [กลุ่ม] สิ่งที่ต้องพูด [รายการ] สิ่งที่ห้ามพูด [ข้อจำกัด] ขอเป็น brief sheet พร้อม caption guideline และ shot list",
      tags: ["Influencer", "รีวิว", "Brief"],
      rating: 4.8,
      uses: 810,
      cover: covers.beauty,
      featured: false,
    },
    {
      id: "ecommerce-product-page",
      title: "เขียนหน้าสินค้าให้น่าซื้อ",
      category: "ecommerce",
      businessType: "สินค้าออนไลน์",
      summary: "สร้างรายละเอียดสินค้าแบบครบ ทั้งจุดขาย ประโยชน์ และ FAQ",
      prompt: "ช่วยเขียนหน้าสินค้าออนไลน์สำหรับ [ชื่อสินค้า] ราคา [ราคา] จุดเด่น [จุดเด่น] กลุ่มลูกค้า [กลุ่ม] ขอชื่อสินค้าแบบ SEO, bullet benefit, รายละเอียดสินค้า, วิธีใช้, FAQ, คำรับประกัน และ CTA",
      tags: ["หน้าสินค้า", "SEO", "Marketplace"],
      rating: 4.9,
      uses: 1440,
      cover: covers.ecommerce,
      featured: true,
    },
    {
      id: "ecommerce-chat-closing",
      title: "ตอบแชตเพื่อปิดการขาย",
      category: "ecommerce",
      businessType: "ร้านค้าออนไลน์",
      summary: "ช่วยตอบลูกค้าที่ถามราคา ค่าส่ง ส่วนลด และลังเลก่อนซื้อ",
      prompt: "ช่วยเขียนชุดคำตอบแชตสำหรับขายสินค้า [ชื่อสินค้า] ราคา [ราคา] โปร [โปร] ข้อกังวลลูกค้าที่พบบ่อย [ข้อกังวล] ขอคำตอบ 10 สถานการณ์ และประโยคปิดการขายแบบสุภาพไม่เร่งเกินไป",
      tags: ["แชต", "ปิดการขาย", "ลูกค้าออนไลน์"],
      rating: 4.9,
      uses: 1350,
      cover: covers.ecommerce,
      featured: true,
    },
    {
      id: "ecommerce-review-post",
      title: "โพสต์รวมรีวิวลูกค้า",
      category: "ecommerce",
      businessType: "สินค้าออนไลน์",
      summary: "เปลี่ยนรีวิวให้เป็นหลักฐานทางสังคมที่ช่วยขาย",
      prompt: "ช่วยเขียนโพสต์รวมรีวิวสินค้า [ชื่อสินค้า] จากรีวิวเหล่านี้ [ใส่รีวิว] ขอจัดกลุ่มรีวิวตาม pain point, เขียน caption, ข้อความบนภาพ, และ CTA ให้ทักสั่งซื้อ โดยไม่กล่าวอ้างเกินจริง",
      tags: ["รีวิว", "Social Proof", "สินค้า"],
      rating: 4.8,
      uses: 940,
      cover: covers.ecommerce,
      featured: false,
    },
    {
      id: "ecommerce-flash-sale",
      title: "แคมเปญ Flash Sale",
      category: "ecommerce",
      businessType: "Marketplace",
      summary: "สร้างความเร่งด่วนแบบพอดี ไม่ดูยัดเยียด",
      prompt: "ช่วยเขียนแคมเปญ Flash Sale สำหรับสินค้า [ชื่อสินค้า] ลดเหลือ [ราคา] จาก [ราคาเดิม] ระยะเวลา [เวลา] จำนวน [จำนวน] ขอ headline 8 แบบ, caption 3 แบบ, ข้อความบนแบนเนอร์ และ push notification สั้น",
      tags: ["Flash Sale", "โปรโมชัน", "เร่งด่วน"],
      rating: 4.8,
      uses: 890,
      cover: covers.ecommerce,
      featured: false,
    },
    {
      id: "local-air-service",
      title: "โปรโมทบริการล้างแอร์รายพื้นที่",
      category: "local-service",
      businessType: "บริการท้องถิ่น",
      summary: "ทำโพสต์ให้ลูกค้าในพื้นที่ทักจองงานได้ทันที",
      prompt: "เขียนโพสต์บริการล้างแอร์สำหรับพื้นที่ [พื้นที่] ราคาเริ่ม [ราคา] จุดเด่น [ช่างตรงเวลา/รับประกัน/อุปกรณ์ครบ] ขอ caption, headline บนภาพ, รายการบริการ, FAQ และ CTA จองคิว",
      tags: ["ล้างแอร์", "บริการพื้นที่", "ช่าง"],
      rating: 4.8,
      uses: 730,
      cover: covers["local-service"],
      featured: true,
    },
    {
      id: "local-cleaning",
      title: "ขายบริการทำความสะอาดบ้าน",
      category: "local-service",
      businessType: "บริการทำความสะอาด",
      summary: "สื่อสารความสะอาด ความไว้ใจ และแพ็กเกจให้ชัด",
      prompt: "ช่วยเขียนโพสต์บริการทำความสะอาดบ้าน/คอนโด [ชื่อบริการ] พื้นที่ให้บริการ [พื้นที่] ราคา [ราคา] จุดเด่น [แม่บ้านประจำ/อุปกรณ์/รีวิว] ขอ caption, แพ็กเกจ 3 ระดับ และคำตอบลูกค้าที่ถามราคา",
      tags: ["ทำความสะอาด", "แพ็กเกจ", "บริการ"],
      rating: 4.7,
      uses: 520,
      cover: covers["local-service"],
      featured: false,
    },
    {
      id: "local-repair",
      title: "โพสต์ช่างซ่อมบ้าน",
      category: "local-service",
      businessType: "งานช่าง",
      summary: "ทำให้บริการดูน่าเชื่อถือและมีขั้นตอนชัดเจน",
      prompt: "เขียนโพสต์บริการช่างซ่อมบ้าน [ประเภทงาน] ในพื้นที่ [พื้นที่] จุดเด่น [ประสบการณ์/ประเมินราคา/รับประกัน] ขอข้อความโพสต์, ขั้นตอนการจอง, FAQ และ CTA ส่งรูปหน้างานเพื่อประเมินราคา",
      tags: ["งานช่าง", "ซ่อมบ้าน", "บริการท้องถิ่น"],
      rating: 4.8,
      uses: 610,
      cover: covers["local-service"],
      featured: false,
    },
    {
      id: "local-logistics",
      title: "โปรโมทบริการขนส่ง/ย้ายบ้าน",
      category: "local-service",
      businessType: "ขนส่ง",
      summary: "ช่วยอธิบายบริการ ราคา และความปลอดภัยให้ลูกค้ามั่นใจ",
      prompt: "ช่วยเขียนโพสต์บริการขนส่ง/ย้ายบ้าน [ชื่อบริการ] พื้นที่ [พื้นที่] รถที่มี [ประเภทรถ] ราคาเริ่ม [ราคา] จุดเด่น [ตรงเวลา/ช่วยยก/ประกันของ] ขอ caption, ข้อความบนภาพ และ checklist ให้ลูกค้าเตรียมตัวก่อนย้าย",
      tags: ["ขนส่ง", "ย้ายบ้าน", "บริการ"],
      rating: 4.7,
      uses: 480,
      cover: covers["local-service"],
      featured: false,
    },
    {
      id: "education-course-sales",
      title: "หน้าโปรโมทคอร์สเรียน",
      category: "education",
      businessType: "คอร์สเรียน",
      summary: "จัดข้อเสนอคอร์สให้ชัดว่าคุ้ม เหมาะกับใคร และเรียนแล้วได้อะไร",
      prompt: "ช่วยเขียนหน้าโปรโมทคอร์ส [ชื่อคอร์ส] สำหรับ [กลุ่มเป้าหมาย] ปัญหาที่แก้ [ปัญหา] ผลลัพธ์หลังเรียน [ผลลัพธ์] ราคา [ราคา] ขอ headline, โครงหน้าเซลส์เพจ, benefit, module outline, FAQ และ CTA สมัครเรียน",
      tags: ["คอร์สเรียน", "Sales Page", "โค้ช"],
      rating: 4.9,
      uses: 980,
      cover: covers.education,
      featured: true,
    },
    {
      id: "education-webinar",
      title: "ชวนสมัคร Webinar ฟรี",
      category: "education",
      businessType: "โค้ช / ที่ปรึกษา",
      summary: "ทำให้คนเห็นคุณค่าก่อนกดลงทะเบียน",
      prompt: "เขียนโพสต์ชวนสมัคร Webinar ฟรีหัวข้อ [หัวข้อ] สำหรับ [กลุ่มเป้าหมาย] สิ่งที่จะได้ [สิ่งที่จะได้] วันเวลา [วันเวลา] ขอ headline 5 แบบ, caption 3 แบบ, ข้อความบนภาพ และ reminder message ก่อนเริ่มงาน",
      tags: ["Webinar", "Lead", "สมัครเรียน"],
      rating: 4.8,
      uses: 690,
      cover: covers.education,
      featured: false,
    },
    {
      id: "education-coach-content",
      title: "คอนเทนต์สร้างตัวตนโค้ช",
      category: "education",
      businessType: "โค้ช / ผู้เชี่ยวชาญ",
      summary: "วางโพสต์ให้ผู้เชี่ยวชาญดูน่าเชื่อถือและมีคนติดตาม",
      prompt: "ช่วยวางแผนคอนเทนต์ 14 วันสำหรับโค้ชด้าน [ความเชี่ยวชาญ] กลุ่มลูกค้า [กลุ่ม] เป้าหมาย [เพิ่มผู้ติดตาม/ขายคอร์ส/นัดปรึกษา] ขอหัวข้อโพสต์ รูปแบบคอนเทนต์ hook และ CTA ของแต่ละวัน",
      tags: ["Personal Brand", "Content Plan", "โค้ช"],
      rating: 4.8,
      uses: 760,
      cover: covers.education,
      featured: false,
    },
    {
      id: "ads-hook-generator",
      title: "สร้าง Hook โฆษณา 20 แบบ",
      category: "ads",
      businessType: "Facebook/TikTok Ads",
      summary: "หาไอเดียเปิดโฆษณาให้หยุดดูใน 1-3 วินาทีแรก",
      prompt: "ช่วยสร้าง Hook โฆษณา 20 แบบสำหรับสินค้า/บริการ [ชื่อ] กลุ่มเป้าหมาย [กลุ่ม] pain point [ปัญหา] ผลลัพธ์ที่ลูกค้าต้องการ [ผลลัพธ์] ขอแยกเป็น 5 กลุ่ม: ปัญหา, ผลลัพธ์, ความเชื่อผิด, social proof, และโปรโมชัน",
      tags: ["Hook", "Ads", "TikTok"],
      rating: 4.9,
      uses: 1520,
      cover: covers.ads,
      featured: true,
    },
    {
      id: "ads-creative-audit",
      title: "วิเคราะห์โฆษณาที่ลงไปแล้ว",
      category: "ads",
      businessType: "Ads Analysis",
      summary: "ช่วยหาจุดอ่อนของข้อความ โครงภาพ และข้อเสนอ",
      prompt: "ช่วยวิเคราะห์โฆษณานี้: [ใส่ข้อความโฆษณา/รายละเอียดภาพ] สินค้า [สินค้า] กลุ่มเป้าหมาย [กลุ่ม] เป้าหมาย [ยอดขาย/ทักแชต/ลงทะเบียน] ขอคะแนน hook, offer, proof, audience signal, CTA และข้อเสนอปรับปรุง 10 ข้อ",
      tags: ["วิเคราะห์ Ads", "Creative", "Andromeda"],
      rating: 4.9,
      uses: 1340,
      cover: covers.ads,
      featured: true,
    },
    {
      id: "ads-caption-variants",
      title: "เขียน Caption Ads 5 มุมขาย",
      category: "ads",
      businessType: "โฆษณาออนไลน์",
      summary: "ได้ข้อความหลายมุมเพื่อเอาไป A/B test",
      prompt: "เขียน Caption Ads 5 มุมขายสำหรับ [สินค้า/บริการ] ราคา [ราคา] กลุ่มเป้าหมาย [กลุ่ม] จุดขาย [จุดขาย] ขอ 5 มุม: ประหยัดเวลา, คุ้มราคา, แก้ปัญหา, รีวิวจริง, โปรจำกัดเวลา พร้อม headline และ CTA ของแต่ละมุม",
      tags: ["Caption", "A/B Test", "Facebook Ads"],
      rating: 4.8,
      uses: 1110,
      cover: covers.ads,
      featured: false,
    },
    {
      id: "video-script-reels-business",
      title: "สคริปต์ Reels โปรโมทธุรกิจ",
      category: "video",
      businessType: "วิดีโอสั้น",
      summary: "ทำสคริปต์คลิปสั้นพร้อม shot list สำหรับธุรกิจไทย",
      prompt: "เขียนสคริปต์ Reels 30 วินาทีสำหรับธุรกิจ [ประเภทธุรกิจ] จุดขาย [จุดขาย] กลุ่มเป้าหมาย [กลุ่มเป้าหมาย] ขอ hook 3 วินาทีแรก, shot list, คำบรรยายบนจอ, voice over, sound direction และ CTA ตอนท้าย",
      tags: ["Reels", "Shorts", "สคริปต์วิดีโอ"],
      rating: 4.8,
      uses: 820,
      cover: covers.video,
      featured: false,
    },
  ];
})();
